<div class="lightbox-backgrond" onclick="Wo_CloseLightbox();"></div>
<div class="lightbox-content post wo_imagecombo_lbox lightpost-<?php echo $wo['story']['id']; ?> story_lightbox" id="post-<?php echo $wo['story']['id']; ?>" data-post-id="<?php echo $wo['story']['id']; ?>">
    <div class="story-img user_story_ tag_view_story_only_main" id="<?php echo $wo['story']['id']; ?>">
        <div class="valign tag_lbox_toolbar">
            <div class="btn btn-mat close-lightbox" onclick="Wo_CloseLightbox();">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                    <path fill="currentColor" d="M7.828 11H20v2H7.828l5.364 5.364-1.414 1.414L4 12l7.778-7.778 1.414 1.414z"></path>
                </svg>
            </div>
        </div>
        <div class="tag_lbox_story_view<?php if ($wo['story']['is_owner']) { ?> more-view<?php } ?> <?php echo isset($wo['story']['ad']) ? 'spons' : ''; ?>">
            <?php if ($wo['story']['story_media'][0]['type'] == 'image') { ?>
                <div class="tag_lbox_blur_img">
                    <div class="tag_lbox_blur_img_innr"><img src="<?php echo $wo['story']['story_media'][0]['filename'].'?cache='.time(); ?>"></div>
                </div>
            <?php } ?>
            <div class="mfp-wrap"><span class="mfp_progress_line_">
                <span class="width_ load"></span><span></div>
            <div class="valign wo_story_header">
                <div class="valign wo_stor_h_info">
                    <img src="<?php echo $wo['story']['user_data']['avatar']; ?>" alt="">
                    <div class="wo_s_h_i_r">
                        <div class="truncate bold user-name">
                            <a href="<?php echo $wo['story']['user_data']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['user_data']['username']; ?>"><?php echo $wo['story']['user_data']['name']; ?></a>
                        </div>
                        <?php if (isset($wo['story']['ad'])) { ?>
                            <span class="ajax-time"><?php echo $wo['lang']['sponsored']; ?></span>
                        <?php } else { ?>
                            <span class="ajax-time"><?php echo Wo_Time_Elapsed_String($wo['story']['posted']); ?></span>
                        <?php } ?>
                    </div>
                </div>
                <div style="display: flex;">
                    <span id="playPauseButton" class="playPauseButton" style="padding: 0 14px;">
                        <svg viewBox="0 0 24 24" width="24" height="24" fill="currentColor" id="on-play" class="on-play"  style="color:#fff;">
                            <path id="playPauseIcon" d="m18.477 12.906-9.711 5.919A1.148 1.148 0 0 1 7 17.919V6.081a1.148 1.148 0 0 1 1.766-.906l9.711 5.919a1.046 1.046 0 0 1 0 1.812z"></path>
                        </svg>
                        <svg viewBox="0 0 24 24" width="24" height="24" fill="currentColor"  id="off-play" class="off-play" style="color: #fff;display:none;">
                            <rect x="7" y="5" width="4" height="14" rx="1.167"></rect><rect x="13" y="5" width="4" height="14" rx="1.167"></rect>
                        </svg>
                    </span>
                    <?php if ($wo['story']['story_media'][0]['filename']) {?>
                        <span id="volumeButton" class="volumeButton">
                            <svg viewBox="0 0 24 24" width="24" height="24" fill="currentColor" id="on-vol" style="color: #fff;">
                                <path d="M13.16 2.124a1.449 1.449 0 0 0-1.563.26l-4.346 4.1a.8.8 0 0 0-.251.58v9.921a.8.8 0 0 0 .255.585l4.35 4.054a1.438 1.438 0 0 0 .97.375 1.466 1.466 0 0 0 .585-.123A1.382 1.382 0 0 0 14 20.6V3.4a1.382 1.382 0 0 0-.84-1.276zM4.25 7A2.25 2.25 0 0 0 2 9.25v5.5A2.25 2.25 0 0 0 4.25 17h.35a.4.4 0 0 0 .4-.4V7.4a.4.4 0 0 0-.4-.4zM16.95 7.05a1 1 0 1 0-1.414 1.414 5.008 5.008 0 0 1 0 7.072 1 1 0 1 0 1.414 1.414 7.009 7.009 0 0 0 0-9.9z"></path><path d="M18.364 4.222a1 1 0 0 0 0 1.414 9.01 9.01 0 0 1 0 12.728 1 1 0 1 0 1.414 1.414 11.012 11.012 0 0 0 0-15.556 1 1 0 0 0-1.414 0z"></path>
                            </svg>
                            <svg viewBox="0 0 24 24" width="24" height="24" fill="currentColor" id="off-vol" style="color: #fff;display:none;">
                                <path d="M13.16 2.124a1.449 1.449 0 0 0-1.563.26l-4.346 4.1a.8.8 0 0 0-.251.58v9.921a.8.8 0 0 0 .255.585l4.35 4.054a1.438 1.438 0 0 0 .97.375 1.466 1.466 0 0 0 .585-.123A1.382 1.382 0 0 0 14 20.6V3.4a1.382 1.382 0 0 0-.84-1.276zM4.25 7A2.25 2.25 0 0 0 2 9.25v5.5A2.25 2.25 0 0 0 4.25 17h.35a.4.4 0 0 0 .4-.4V7.4a.4.4 0 0 0-.4-.4zM21.707 9.293a1 1 0 0 0-1.414 0L19 10.586l-1.293-1.293a1 1 0 0 0-1.414 1.414L17.586 12l-1.293 1.293a1 1 0 1 0 1.414 1.414L19 13.414l1.293 1.293a1 1 0 0 0 1.414-1.414L20.414 12l1.293-1.293a1 1 0 0 0 0-1.414z"></path>
                            </svg>
                        </span>
                    <?php }?>
                </div>


                <?php if ($wo['story']['is_owner']) { ?>
                    <div class="btn btn-mat wo_stor_h_opts <?php echo isset($wo['story']['ad']) ? 'd-none' : ''; ?>" onclick="Wo_DeleteStatus(<?php echo $wo['story']['id']; ?>)">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z"></path>
                        </svg>
                    </div>
                <?php } ?>
                <div class="btn btn-mat wo_stor_h_opts tag_close_story_altr" onclick="Wo_CloseLightbox();">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M18.3 5.71c-.39-.39-1.02-.39-1.41 0L12 10.59 7.11 5.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41L10.59 12 5.7 16.89c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0L12 13.41l4.89 4.89c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"></path>
                    </svg>
                </div>
            </div>
            <div class="tag_lbox_img_innr">
                <span class="btn btn-mat changer previous-btn" onclick="Get_PreviousStory('<?php echo $wo['story']['id']; ?>','<?php echo $wo['story_type']; ?>')"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                        <path fill="currentColor" d="M10.828 12l4.95 4.95-1.414 1.414L8 12l6.364-6.364 1.414 1.414z" />
                    </svg></span>
                <span class="btn btn-mat changer next-btn" onclick="Get_NextStory('<?php echo $wo['story']['id']; ?>','<?php echo $wo['story_type']; ?>')"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                        <path fill="currentColor" d="M13.172 12l-4.95-4.95 1.414-1.414L16 12l-6.364 6.364-1.414-1.414z" />
                    </svg></span>
                <div class="spons_prnt <?php echo isset($wo['story']['ad']) ? 'rads-'.$wo['story']['ad']['bidding'] : ''; ?>" id="<?php echo isset($wo['story']['ad']) ? $wo['story']['ad']['id'] : ''; ?>">
                    <?php if (isset($wo['story']['ad'])) { ?>
                        <a href="<?php echo $wo['story']['ad']['url']; ?>" class="main" target="_blank">
                            <?php echo Wo_UrlDomain($wo['story']['ad']['url']); ?> <svg xmlns="http://www.w3.org/2000/svg" height="15" viewBox="0 -960 960 960" width="15">
                                <path fill="currentColor" d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h240q17 0 28.5 11.5T480-800q0 17-11.5 28.5T440-760H200v560h560v-240q0-17 11.5-28.5T800-480q17 0 28.5 11.5T840-440v240q0 33-23.5 56.5T760-120H200Zm560-584L416-360q-11 11-28 11t-28-11q-11-11-11-28t11-28l344-344H600q-17 0-28.5-11.5T560-800q0-17 11.5-28.5T600-840h240v240q0 17-11.5 28.5T800-560q-17 0-28.5-11.5T760-600v-104Z" />
                            </svg>
                        </a>
                    <?php } ?>
                    <div id="draggableHelper" class="dragable">
                        <?php if ($wo['story']['story_media'][0]['type'] == 'image') { ?>
                            <img src="<?php echo $wo['story']['story_media'][0]['filename'].'?cache='.time(); ?>" alt="media" class="<?php echo isset($wo['story']['ad']) ? 'rads-'.$wo['story']['ad']['bidding'] : ''; ?>" id="<?php echo isset($wo['story']['ad']) ? $wo['story']['ad']['id'] : ''; ?>" >
                        <?php } else { ?>
                            <video preload="auto" autoplay playsinline style="width: 100%; height: 88%;" data-story-video="<?php echo $wo['story']['story_media'][0]['id']; ?>" id="video_story">
                                <source src="<?php echo $wo['story']['story_media'][0]['filename']; ?>" type='video/mp4'>
                                <source src="<?php echo $wo['story']['story_media'][0]['filename']; ?>" type='video/webm'>
                            </video>

                        <?php } ?>
                    </div>
                </div>
                <?php // if (!$wo['story']['is_owner']) {
                ?>
                <?php if (!empty($wo['story']['description'])) { ?>
                    <div class="text-center draggableHelper_story_content"><?php echo $wo['story']['description']; ?></div>
                <?php } ?>
                <?php // }
                ?>
                <?php if ($wo['story']['is_owner']) { ?>
                    <button class="btn btn-mat tag_view_count_story_mobi" onclick="$('.lightpost-<?php echo $wo['story']['id']; ?>').addClass('stor_view_active');"><?php echo (!empty($wo['story']['view_count'])) ? $wo['story']['view_count'] : 0; ?> <?php echo $wo['lang']['views']; ?></button>
                <?php } ?>
            </div>
        </div>
        <div class="valign tag_story_react <?php echo isset($wo['story']['ad']) ? 'd-none' : ''; ?>">
            <?php if (!$wo['story']['is_owner'] && !isset($wo['story']['ad'])) { ?>
                <a href="javascript:void(0)" class="btn btn-mat btn-reply-story" onclick="Wo_OpenChatTab(<?php echo $wo['story']['user_id']; ?>,0,0,0,0,<?php echo $wo['story']['id']; ?>);">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M10,9V5L3,12L10,19V14.9C15,14.9 18.5,16.5 21,20C20,15 17,10 10,9Z"></path>
                    </svg> <?php echo $wo['lang']['reply']; ?>
                </a>
                <div class="particlescontainer">
                    <?php if (!empty($wo['reactions_types'])) {
                        foreach ($wo['reactions_types'] as $key => $value) {
                            if ($value['status'] == 1) {
                                ?>
                                <div class="valign reaction reaction-<?php echo $value['id']; ?> emoji-btn" data-emoji="<?php echo $value['id']; ?>" data-reaction="<?php echo $value['name']; ?>" data-reaction-id="<?php echo $value['id']; ?>" data-reaction-lang="<?php echo $value['name']; ?>" title="<?php echo $value['name']; ?>" data-post-id="<?php echo $wo['story']['id']; ?>" onclick="Wo_RegisterStoryReaction(this,'<?php echo $value['wowonder_small_icon']; ?>',<?php echo $value['is_html']; ?>);">
                                    <?php if (preg_match('/<[^<]+>/', $value['wowonder_icon'], $m)) {
                                        echo $value['wowonder_icon'];
                                    } else { ?>
                                        <img src="<?php echo $value['wowonder_icon']; ?>">
                                    <?php } ?>
                                </div>
                    <?php }
                            }
                    } ?>
                </div>

            <?php } ?>
            <?php if ($wo['story']['is_owner']) { ?>
                <div class="like-stat stat-item post-like-status">
                    <span class="like-emo post-reactions-icons-<?php echo $wo['story']['id']; ?>" data-no-react="<?php echo $wo['lang']['no_reactions']; ?>"><?php echo Wo_GetPostReactions($wo['story']['id'], 'story'); ?></span>
                </div>
            <?php } ?>
        </div>
    </div>

    <?php if ($wo['story']['is_owner']) { ?>
        <div class="tag_story_side tag_view_story_only_side">
            <h2 class="tag_page_title"><button type="button" class="btn lbox_coms_navigation" onclick="$('.lightpost-<?php echo $wo['story']['id']; ?>').removeClass('stor_view_active');"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                        <path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" fill="currentColor"></path>
                    </svg></button><?php echo (!empty($wo['story']['view_count'])) ? $wo['story']['view_count'] : 0; ?> <?php echo $wo['lang']['views']; ?></h2>
            <div class="tag_lbox_story_views">
                <div class="views_container_">
                    <?php if (!empty($wo['story']['story_views'])) {
                        foreach ($wo['story']['story_views'] as $key => $value) { ?>
                            <div class="story_views_" id="<?php echo $value['id']; ?>">
                                <div class="valign story_view_list">
                                    <img src="<?php echo $value['avatar']; ?>" alt="">
                                    <div class="bold user-name">
                                        <a href="<?php echo $value['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $value['username']; ?>"><?php echo $value['name']; ?></a>
                                        <div>
                                            <time><?php echo $value['seenOn']; ?></time>
                                        </div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                    <?php }
                        } ?>
                </div>
                <?php if (!empty($wo['story']['story_views']) && count($wo['story']['story_views']) > 9) { ?>
                    <div class="load-more" onclick="Wo_GetMoreStoryViews(<?php echo $wo['story']['id']; ?>,this);">
                        <button class="btn btn-default text-center pointer" id="load_more_friends">
                            <span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                    <path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path>
                                </svg></span> <?php echo $wo['lang']['load_more']; ?>
                        </button>
                    </div>
                <?php } ?>
            </div>
        </div>
    <?php } else { ?>
        <?php if (Wo_IsMobile() == false) { ?>
            <div class="tag_story_side tag_view_story_only_side">
                <h2 class="tag_page_title"><?php echo $wo['lang']['stories']; ?></h2>
                <div class="tag_lbox_stories">
                    <ul class="list-unstyled valign status-list">
                        <?php if ($wo['config']['can_use_story']) { ?>
                            <li class="create_new">
                                <a href="<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>" data-ajax="?link1=create-status">
                                    <img src="<?php echo $wo['user']['avatar']; ?>" alt="<?php echo $wo['user']['name']; ?>">
                                    <span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                            <path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" />
                                        </svg></span>
                                </a>
                                <p class="truncate"><?php echo $wo['lang']['create_story']; ?></p>
                            </li>
                        <?php } ?>
                        <?php
                            if ($wo['config']['user_status'] == 1) {
                                $get_user_status = Wo_GetFriendsStatus(['limit' => 400]);
                                if (!empty($get_user_status)) {
                                    ?>
                            <?php
                                            foreach ($get_user_status as $key => $wo['user_status']) {
                                                echo Wo_LoadPage('home/lightbox-user-status');
                                            }
                                }
                                ?>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
</div>

<script>
    $(document).keydown(function(e) {
        if (e.keyCode == 27) {
            Wo_CloseLightbox();
        }
        $(".lighbox.textarea").triggeredAutocomplete({
            hidden: '#hidden_inputbox_comment_lighbox',
            source: Wo_Ajax_Requests_File() + "?f=mention",
            trigger: "@"
        });
    }); 
    $(document).ready(function() {
        var getRandomInteger = function(min, max) {
            return Math.floor(Math.random() * (max - min + 1) + min);
        };

        var fbreactions = []; 

        $(".emoji-btn").on("click", function() {
            var emoji = $(this).data("emoji");
            if (emoji == 1) emoji = "like";
            else if (emoji == 2) emoji = "love";
            else if (emoji == 3) emoji = "happy";
            else if (emoji == 4) emoji = "wow";
            else if (emoji == 5) emoji = "sad";
            else emoji = "angry";
            console.log(emoji);
            $(".particlescontainer").append("<span class='particle " + emoji + "' style='opacity:0;'></span>");
            $(".particle." + emoji).animate({
                opacity: 1,
            }, 0);
        });

        var particleInterval;
        var generateParticles = function () {
            $(".particlescontainer").append(
                "<span class='particle " + 
                fbreactions[getRandomInteger(0, fbreactions.length - 1)]
                + "'></span>"
            );

            $(".particle").toArray().forEach(function(particle) {
                $(particle).animate({
                    left: getRandomInteger(0, $("body").width()),
                }, getRandomInteger(10, 30), function () {
                    $(particle).animate({
                        top: -100 + "%",
                        opacity: 0
                    }, getRandomInteger(5000, 8000), function () {
                        $(particle).remove();
                    })
                });

                $(particle).on("mouseenter", function () {
                    $(this).css({
                        transform: "scale(1.5)",
                        transition: "transform 0.3s ease"
                    });
                }).on("mouseleave", function () {
                    $(this).css({
                        transform: "scale(1)",
                        transition: "transform 0.3s ease"
                    });
                }).on("click", function () {
                    $(this).remove();
                });
            });

            particleInterval = setTimeout(generateParticles, getRandomInteger(400, 600));
        };

        generateParticles();

        $(window).on("blur", function () {
            clearInterval(particleInterval);
        });


    });

    $(document).ready(function() {
        var mediaElement = document.getElementById('video_story'); 
        var volumeButton = $('#volumeButton');
        var onVol = $('#on-vol');
        var offVol = $('#off-vol');
        
        volumeButton.on('click', function() {
            if (mediaElement.muted) {
                mediaElement.muted = false;
                onVol.css('display', 'block');
                offVol.css('display', 'none');
            } else {
                mediaElement.muted = true;
                onVol.css('display', 'none');
                offVol.css('display', 'block');
            }
        });

    });

</script>