<?php 

$page           = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$db->pageLimit  = 50;
$link = '';


$versions = $db->objectbuilder()->paginate(T_VERSION_APP, $page);

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
  header("Location: " . Wo_LoadAdminLinkSettings('app-version'));
  exit();
}

?>
<div class="container-fluid">
    <div>
        <h3>App Version</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">App Version</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
				<button class="btn btn-info float-right" id="add_new_gender">Add new Version</button>
                  <h6 class="card-title">Manage & Edit App version</h6>
                    <div class="clearfix"></div>
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                              <th>ID</th>
  			                  <th>Version</th>
  			                  <th>Type </th>
  			                  <th>Status</th>
  			                  <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                              <?php 
        				                foreach ($versions as $version) {
        				                    
                                  $wo['version'] = $version;
        				                  echo Wo_LoadAdminPage('app-version/list');
        				                }
				                      ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                      <div class="pull-left">
                        <span>
                          <?php echo "Showing $page out of " . $db->totalPages; ?>
                        </span>
                      </div>
                      <div class="pull-right">
                        <nav>
                          <ul class="pagination">
                            <li>
                              <a href="<?php echo Wo_LoadAdminLinkSettings('app-version?page-id=1').$link; ?>" data-ajax="?path=app-version&page-id=1<?php echo($link); ?>" class="waves-effect" title='First Page'>
                                  <i class="material-icons">first_page</i>
                              </a>
                            </li>
                            <?php if ($page > 1) {  ?>
                              <li>
                                  <a href="<?php echo Wo_LoadAdminLinkSettings('app-version?page-id=' . ($page - 1)).$link; ?>" data-ajax="?path=app-version&page-id=<?php echo($page - 1) ?><?php echo($link); ?>" class="waves-effect" title='Previous Page'>
                                      <i class="material-icons">chevron_left</i>
                                  </a>
                              </li>
                            <?php  } ?>

                            <?php 
                              $nums       = 0;
                              $nums_pages = ($page > 4) ? ($page - 4) : $page;

                              for ($i=$nums_pages; $i <= $db->totalPages; $i++) { 
                                if ($nums < 20) {
                            ?>
                              <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                <a href="<?php echo Wo_LoadAdminLinkSettings('app-version?page-id=' . ($i)).$link; ?>" data-ajax="?path=app-version&page-id=<?php echo($i) ?><?php echo($link); ?>" class="waves-effect">
                                  <?php echo $i ?>   
                                </a>
                              </li>

                            <?php } $nums++; }?>

                            <?php if ($db->totalPages > $page) { ?>
                              <li>
                                  <a href="<?php echo Wo_LoadAdminLinkSettings('app-version?page-id=' . ($page + 1)).$link; ?>" data-ajax="?path=app-version&page-id=<?php echo($page + 1) ?><?php echo($link); ?>" class="waves-effect" title="Next Page">
                                      <i class="material-icons">chevron_right</i>
                                  </a>
                              </li>
                            <?php } ?>
                            <li>
                              <a href="<?php echo Wo_LoadAdminLinkSettings('app-version?page-id=' . ($db->totalPages)).$link; ?>" data-ajax="?path=app-version&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>" class="waves-effect" title='Last Page'>
                                  <i class="material-icons">last_page</i>
                              </a>
                            </li>
                          </ul>
                        </nav>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    
    <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">

    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Delete Version?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this Version?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Delete</button>
                </div>
            </div>
        </div>
    </div>
<div class="modal fade" id="langsModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="langsModalLabel">Add New Version</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="langsModalAlert"></div>
                <form class="langsModalForm" method="POST">
                    <div class="form-group">
                        <div class="form-lins">
                            <label class="form-lasbel">Type</label>
                            <input type="text" name="type" id="type" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-lins">
                            <label class="form-lasbel">Version</label>
                            <input type="text" name="version_number" id="version_number" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-lins">
                            <label class="form-lasbel">Status</label>
                            <select name="status" id="status" class="form-control">
                                <option value="1">Active</option>
                                <option value="0">In Active</option>
                            </select>
                        </div>
                    </div>
                    <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal">CLOSE</button>
                <button type="button" class="btn btn-primary" onclick="Wo_SubmitAddGenderForm();">SAVE CHANGES</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="country_adsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal_content_back">
      <div class="modal-header">
        <h5 class="modal-title">Edit Country Cost</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="country_ads_form_alert"></div>
        <form class="country_ads_form" method="POST" id="modal-body-langs">
            <input type="hidden" id="edit_id" name="edit_id" value="">
          <div class="row">
                <div class="col-md-12">
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <label class="form-label">Type</label>
                            <input type="text" name="edit_type" class="form-control" value="" id="edit_type">
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <label class="form-label">Version</label>
                            <input type="text" name="edit_version_number" class="form-control" value="" id="edit_version_number">
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <label class="form-lasbel">Status</label>
                            <select name="edit_status" id="edit_status" class="form-control">
                                <option value="1">Active</option>
                                <option value="0">In Active</option>
                            </select>
                        </div>
                    </div>
                </div>
          </div>

          <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
          <div class="modal-footer">
        
        <button type="button" class="btn btn-primary modal_close_btn" data-dismiss="modal">CLOSE</button>
        <button type="submit" class="btn btn-success" id="edit_custom_field_button">SAVE CHANGES</button>
      </div>
        </form>
        
      </div>
      
    </div>
  </div>
</div>

<script>

function getVersion(id) {
    $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_version', {
        hash_id: $('input[name=hash_id]').val(),
        id: id
    }, function (data) {
        if (data.status == 200) {
            $('#edit_type').val(data.data.type);
            $('#edit_version_number').val(data.data.version_number);
            $('#edit_id').val(data.data.id);
            $('#edit_status').val(data.data.status);
            $('#country_adsModal').modal('show');
        } else {
        }
    });
}

var edit_custom_field_form = $('form.country_ads_form');

edit_custom_field_form.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=edit_verion',
    beforeSend: function() {
        $('#edit_custom_field_button').text("Please wait..");
    },
    success: function(data) {
        console.log(data)
        if (data.status == 200) {
            $('#edit_custom_field_button').text('SAVE CHANGES');
            $('.country_ads_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> successfully edited</div>');
            setTimeout(function () {
                $('.country_ads_form_alert').empty();
            }, 2000);
            window.location.reload();
        }
        else{
          $('.country_ads_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> '+data.message+'</div>');
            setTimeout(function () {
                $('.country_ads_form_alert').empty();
            }, 2000);
        }
    }
});
    
function Wo_SubmitAddGenderForm() {
    $('.langsModalForm').submit();
}
$(function () {
    var form_gender_settings = $('form.langsModalForm');
    form_gender_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_version&hash=' + $('.main_session').val(),
        beforeSend: function() {
            $('.btn-save').text('Please wait..');
        },
        success: function(data) {
            
            if (data.status == 200) {
                $('.btn-save').text('SAVE CHANGES');
                $('#langsModal').modal('hide');
                location.reload();
            }
            else{
                $('.btn-save').text('SAVE CHANGES');
                $('.langsModalAlert').html('<div class="alert alert-danger">'+data.message+'</div>');
                setTimeout(function () {
                    $('.langsModalAlert').empty();
                }, 2000);
            }
            $("#langsModal").animate({ scrollTop: 0 }, 100);

        }
    });
});

$(document).on('click', '#add_new_gender', function(event) {
    $('#langsModal').modal('show');
});

function Wo_DeleteVersion(version_id,type = 'show') {
    console.log(version_id,$('#hash_id').val())
  if (type == 'hide') {
    $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeleteVersion('"+version_id+"')");
    $('#DeleteModal').modal('show');
    return false;
  }
  hash_id = $('#hash_id').val();
  $('#versionID_' + version_id).fadeOut(300, function() {
    $(this).remove();
  });
  console.log(  $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'delete_version', version_id: version_id}));
  $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'delete_version', version_id: version_id});
}
</script>

