<style>
.contact-list {
    margin-bottom: 15px;
}

.contact-list .input-group {
    display: flex;
}

.contact-list .input-group div {
    margin-right: 10px;
}

.contact-type-wrapper {
    flex: 1; /* Take the remaining space in the input-group */
}

.custom-dropdown {
    width: 40% !important; /* Set the width to 100% */
    padding: 5px; /* Add padding for visual appeal */
}
</style>
<div class="wow_sett_content">
	<form  method="post" class="form-horizontal setting-information-form tag_field_full_margin">
		<div class="setting-information-alert setting-update-alert"></div>
		<div class="row">
			<div class="col-xl-12">
				<label class="tag_field">
					<input name="company" id="company" type="text" placeholder=" " value="<?php echo $wo['setting']['company']?>" autocomplete="off">
					<span><?php echo $wo['lang']['company'] ?></span>
				</label>
			</div>
			<div class="col-xl-12">
				<label class="tag_field">
					<input id="address" name="address" type="text" placeholder=" " value="<?php echo $wo['setting']['address']?>" autocomplete="off">
					<span><?php echo $wo['lang']['location'] ?></span>
					<?php if ($wo['config']['yandex_map'] == 1) { ?>
						<div class="yandex_search_page"></div>
					<?php } ?>
				</label>
			</div>
		</div>
		<div class="row">
    <div class="col-xl-12">
          <!-- Contact Type -->
          <label class="tag_field wow_form_fields contact-list">
                <select name="contact_type" id="contact_type" class="form-control custom-dropdown">
                  <option value="whatsapp" <?php echo ($wo['setting']['contact_type'] == 'whatsapp') ? 'selected' : ''; ?>>--<?php echo $wo['lang']['whatsapp']; ?>--</option>
                  <option value="phone" <?php echo ($wo['setting']['contact_type'] == 'phone') ? 'selected' : ''; ?>>--<?php echo $wo['lang']['phone_number']; ?>--</option>
                  <option value="website" <?php echo ($wo['setting']['contact_type'] == 'website') ? 'selected' : ''; ?>>--<?php echo $wo['lang']['website']; ?>--</option>
                  <!-- Add more options as needed -->
                </select>
                <!-- WhatsApp Input Field -->
                <label class="tag_field" id="whatsapp_field_edit" <?php echo ($wo['setting']['contact_type'] == 'whatsapp') ? 'style="display: inline-block;width: 100% !important;"' : 'style="display: none;width: 100% !important;"'; ?>>
                  <input id="whatsapp_number_edit" name="whatsapp_number" value="<?php echo $wo['setting']['whatsapp_number']; ?>" placeholder="<?php echo $wo['lang']['whatsapp']; ?> : e.g.: +1234567890" type="text">
                </label>
                <!-- Phone Input Field -->
                <label class="tag_field" id="phone_field_edit" <?php echo ($wo['setting']['contact_type'] == 'phone') ? 'style="display: inline-block;width: 100% !important;"' : 'style="display: none;width: 100% !important;"'; ?>>
                  <input id="phone_number_edit" name="phone" value="<?php echo $wo['setting']['phone']; ?>" placeholder="<?php echo $wo['lang']['phone_number']; ?> : e.g.: +1234567890" type="text">
                </label>
                <!-- website Input Field -->
                <label class="tag_field" id="website_field_edit" <?php echo ($wo['setting']['contact_type'] == 'website') ? 'style="display: inline-block;width: 100% !important;"' : 'style="display: none; width: 100% !important;"'; ?>>
                  <input id="website_contact_edit" name="website" value="<?php echo $wo['setting']['website']; ?>" placeholder="<?php echo $wo['lang']['website']; ?> <?php echo $wo['lang']['site_eg'];?>"  type="text">
                </label>

          </label>
      </div>
		</div>
		<label class="tag_field">
			<?php $text = br2nl($wo['setting']['about']); ?>         
			<textarea id="page_description" name="page_description" placeholder=" " rows="4"><?php echo $text;?></textarea>
			<span><?php echo $wo['lang']['about'] ?></span>
		</label>

		<div class="text-center">
			<button type="submit" class="btn btn-main btn-mat btn-mat-raised disable_btn"><?php echo $wo['lang']['save']; ?></button>
		</div>
		<input type="hidden" name="page_id" value="<?php echo $wo['setting']['page_id'];?>">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>
<script type="text/javascript">
   $(function() {
    
    $('#contact_type').change();
    $('#contact_type').change(function () {
        var selectedContactType = $(this).val();
        $('#whatsapp_field_edit, #phone_field_edit, #website_field_edit').hide();
        $('#' + selectedContactType + '_field_edit').show();
    });

     $('form.setting-information-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=pages&s=update_information_setting',
       beforeSend: function() {
         $('.setting-information-form').find('.disable_btn').attr('disabled','disabled');
       },
       success: function(data) {
         if (data.status == 200) {
           scrollToTop();
           $('.setting-information-alert').html('<div class="alert alert-success">' + data.message + '</div>');
           $('.alert-success').fadeIn('fast', function() {
             $(this).delay(2500).slideUp(500, function() {
               $(this).remove();
             });
           });
         } else {
           var errors = data.errors.join("<br>");
           scrollToTop();
           $('.setting-profile-alert').html('<div class="alert alert-danger">' + errors + '</div>');
           $('.alert-danger').fadeIn(300);
         }
         $('.setting-information-form').find('.disable_btn').removeAttr("disabled");
       }
     });
   });
   <?php if ($wo['config']['google_map'] == 1) { ?>
   var pac_input = document.getElementById('address');
     (function pacSelectFirst(input) {
       // store the original event binding function
       var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;
       function addEventListenerWrapper(type, listener) {
         // Simulate a 'down arrow' keypress on hitting 'return' when no pac suggestion is selected,
         // and then trigger the original listener.
         if(type == "keydown") {
           var orig_listener = listener;
           listener = function (event) {
             var suggestion_selected = $(".pac-item-selected").length > 0;
             if(event.which == 13 && !suggestion_selected) {
               var simulated_downarrow = $.Event("keydown", {
                 keyCode: 40,
                 which: 40
               });
               orig_listener.apply(input, [simulated_downarrow]);
             }
             orig_listener.apply(input, [event]);
           };
         }
         // add the modified listener
         _addEventListener.apply(input, [type, listener]);
       }
       if(input.addEventListener)
         input.addEventListener = addEventListenerWrapper;
       else if(input.attachEvent)
         input.attachEvent = addEventListenerWrapper;
     })(pac_input);
   
     $(function () {
        var autocomplete = new google.maps.places.Autocomplete(pac_input);
     });
   <?php } ?>
   <?php if ($wo['config']['yandex_map'] == 1) { ?>
  $(function() {
    
    $('#address').on( "keydown", function() {
      let self = this;
      var myGeocoder = ymaps.geocode($(this).val());
      myGeocoder.then(
          function (res) {
            if (res.geoObjects.getLength() == 0) {
              $('.yandex_search_page').html('');
            }
            else{
              let html = '';
              for (var i = 0; i < res.geoObjects.getLength(); i++) {
                html += '<p class="pointer" onclick="AddYandexResult(\'#address\',this,\'.yandex_search_page\')">'+res.geoObjects.get(i).properties.get('name')+'</p>';
              }
              $('.yandex_search_page').html(html);
            }
          },
          function (err) {
              $('.yandex_search_page').html('');
          }
      );
    });
  });
<?php } ?>
</script>